//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deliver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public int id { get; set; }
        public System.DateTime orderedDate { get; set; }
        public System.DateTime shipedDate { get; set; }
        public System.DateTime deliveredDate { get; set; }
        public string trackingNumber { get; set; }
        public string originAddress { get; set; }
        public System.Data.Entity.Spatial.DbGeography originPoint { get; set; }
        public string destinationAddress { get; set; }
        public System.Data.Entity.Spatial.DbGeography destinationPoint { get; set; }
        public Nullable<int> vendorId { get; set; }
        public System.Data.Entity.Spatial.DbGeography lastPointReported { get; set; }
        public System.DateTime estimatedDeliverDate { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
